ExprTkFunctionParser: Fix missing sstream include
Fixes build with exprtk 0.0.2:
vtkExprTkFunctionParser.cxx:480:25: error: aggregate ‘std::stringstream parsingErrorStream’ has incomplete type and cannot be defined
2023-02-24T13:39:45.8563290Z   480 |       std::stringstream parsingErrorStream;