Fix c++20 compile error in vtkPlotBag
The error was generated by Visual Studio 2022 /std:c++20:
error C2445: result type of conditional expression is ambiguous:
types 'vtkStdString' and 'const char [2]' can be converted to
multiple common types