Add MergedTextureWidth to limit max texture width.
Avoid error in Cesium.js for the jacksonville dataset:
DeveloperError: Width must be less than or equal to the maximum
texture size (16384).  Check maximumTextureSize.

The reason is that some textures for this dataset are 8000 x 80
but the merging code assumes them approximately square.