Reshape VTKArrays so that they can be combined through operators.
An array G of shape (n,3) resulted from computing the
gradient on a scalar array S of shape (n,) cannot be added together without
reshaping.
G + expand_dims(S,1) works,
G + S gives an error:
ValueError: operands could not be broadcast together with shapes (n,3) (n,)

This commit performs this reshape operation automatically by appending 1s
to the dimensions of the array with fewer dimensions.

Change-Id: I0a0eaeecf5063fac1c8b71b9d32472bbc41d42c8