Fix conversion from float to enum
Fix issue when building with VS2017:
 error C2440: Conversions between enumeration and floating point values
 are no longer allowed.