Fix vtkLoadPythonTkWidgets error with Python 2.
After the changes to make this module work with Python 3, it gives the
following error under Python 2.7:

UnboundLocalError: local variable 'unicode' referenced before assignment

Creating a local variable from the builtin 'unicode' fixes the issue.