Fix undefined reference to vtkCallbackCommand in InteractionWidgets
- When compiling vtkAbstractWidgetSerDesHelper.cxx with msvc,
  it complains that vtkCallbackCommand::Reset is not defined
  with the compiler stack trace starting from the destructor of
  vtkCameraOrientationWidget and vtkCameraPathWidget
- Since that variable is using vtkNew, fix it by moving the
  destructor implementation of these classes into the C++ file
  where vtkCallbackCommand is guaranteed to be defined.