SOADataArrayTemplate: Fix MinGW build
Moves some some methods to .txx to avoid undefined references:
[ 32%] Linking CXX shared library ../../bin/libvtkCommonDataModel-9.5.dll
.../x86_64-w64-mingw32/bin/ld: CMakeFiles/CommonDataModel.dir/objects.a(vtkBoundingBox.cxx.obj):vtkBoundingBox:(.text+0x102c3):
 undefined reference to `vtkSOADataArrayTemplate<double>::GetTypedTuple(long long, double*) const'

Presumably caused by: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/12551 (vtkArrayDispatch: Clean dispatch flags)