Partially revert "vtkDeprecation: Always use [[deprecated]] for deprecation"
This reverts commit 2f24f597854e3e42ef65dc0493c11784218d1514.

if fixes the terror that the compiler mix [[deprecated]] with visibility macros,
and cause parser like below

error: expected identifier before '__attribute__'
// class [[deprecated("deprecated")]] __attribute__((visibility("default"))) Foo {};