Fix VS2013 build issues.
Xdmf3 was failing with "fatal error C1001: An internal error has occurred
in the compiler". The issue was the code was using resize() methods
without calling initialize which is needed for boost::variant to pick
container type. This fixes the issue by using initialize() instead of
resize() for the offending calls.