Resolve ambiguous call issues setting nlohmann::json values from vtkStdString
On the Intel oneAPI 2021 compilers, these calls were leading to compilation
errors due to ambiguous calls to __is_path_src:

bits/fs_path.h:119:16: error: call to '__is_path_src' is ambiguous

    : decltype(__is_path_src(std::declval<_Source>(), 0))

Invoking c_str() resolves the ambiguity.