ci: python update numpy version for windows
Required due to the newer setuptools dependency
Otherwise installing numpy fails fails with:

AttributeError: module 'pkgutil' has no attribute 'ImpImporter'.