Fix link error in iOS examples
Fix link error like the following when building the iOS examples:

    Undefined symbols for architecture x86_64:
      "vtkInteractorStyleMultiTouchCamera::New()", referenced from:
          -[MyGLKViewController setupPipeline] in MyGLKViewController.o
    ld: symbol(s) not found for architecture x86_64

Because the examples use vtkInteractorStyleMultiTouchCamera, the
InteractionStyle module must be enabled.