COMP: define a portable ExitEvent
Windows VS71 reports:
    iRen.AddObserver("ExitEvent", exit)
TypeError: a callable object is required

This patch provides a portable alternative

Change-Id: I2994530a458b776e4f9d6db6963536983044ce34