ENH: TestChangeInformation does not print error message.
vtkImageChangeInformation has both its inputs set using SetInputConnection
and SetInformationInputData. However, the first time the pipeline is run
the data object for the second connection is empty.
The error messages were:
ERROR: In /home/danlipsa/src/VTK/Common/ExecutionModel/vtkStreamingDemandDrivenPipeline.cxx, line 857
vtkStreamingDemandDrivenPipeline (0x2817f00): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x2817a50) is 0 255 0 255 0 0, which is outside the whole extent 0 -1 0 -1 0 -1.

ERROR: In /home/danlipsa/src/VTK/Common/ExecutionModel/vtkTrivialProducer.cxx, line 264
vtkTrivialProducer (0x2817a50): This data object does not contain the requested extent.