ci: update aiohttp in windows venv
The previous pinned version failed in python 3.13 due to removed symbols
and different signatures in CPython functions:

error C2039:: 'op_digit': is not a member of '_longobject'
error C2198: 'int _PyLong_AsByteArray': too few arguments to call